from pathlib import Path
p=Path("silent-camera-safari.html")
s=p.read_text(encoding="utf-8")
code=r'''
/* ===== Attachment batch export / share ===== */
function safeFilePart(v){ return (v||'메모').replace(/[\\/:*?"<>|]/g,'_').replace(/\s+/g,' ').trim().slice(0,60)||'메모'; }
function mediaExt(m){ const t=(m&&m.blob&&m.blob.type)||''; if(m.kind==='video')return t.includes('mp4')?'mp4':t.includes('quicktime')?'mov':'webm'; if(m.kind==='audio')return t.includes('mp4')?'m4a':t.includes('mpeg')?'mp3':t.includes('wav')?'wav':'webm'; return t.includes('png')?'png':t.includes('heic')?'heic':t.includes('webp')?'webp':'jpg'; }
async function exportFilesForNotes(targetNotes){ const out=[]; for(const n of targetNotes){ const title=safeFilePart(n.title||'메모'); let i=0; for(const m of (n.media||[])){ if(!m||!m.blob)continue; i++; const src=await mediaBytes(m.blob); const blob=new Blob([src.buf.slice(0)],{type:src.type}); const kind=m.kind==='video'?'video':m.kind==='audio'?'audio':'photo'; out.push({name:title+'_'+String(i).padStart(2,'0')+'_'+kind+'.'+mediaExt(m),blob,type:blob.type||'application/octet-stream'}); } } return out; }
function crc32(bytes){ let c=0xffffffff; for(let i=0;i<bytes.length;i++){c^=bytes[i];for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);} return (c^0xffffffff)>>>0; }
function u16(n){return[n&255,(n>>>8)&255];} function u32(n){return[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255];}
async function makeZip(entries){ const enc=new TextEncoder(),locals=[],centrals=[];let offset=0; for(const e of entries){const name=enc.encode(e.name),data=new Uint8Array(await e.blob.arrayBuffer()),crc=crc32(data);const local=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0x0800),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...name]);locals.push(local,data);const central=new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0x0800),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...name]);centrals.push(central);offset+=local.length+data.length;} const cs=centrals.reduce((a,b)=>a+b.length,0),end=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(entries.length),...u16(entries.length),...u32(cs),...u32(offset),...u16(0)]);return new Blob([...locals,...centrals,end],{type:'application/zip'}); }
function downloadBlob(blob,name){const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>{try{URL.revokeObjectURL(u);}catch(e){}},60000);}
async function runBatchExport(targetNotes,mode){closeSheet();try{showToast('첨부파일 준비 중…');const entries=await exportFilesForNotes(targetNotes);if(!entries.length){showToast('내보낼 첨부파일이 없습니다');return;}if(mode==='share'){const files=entries.map(e=>new File([e.blob],e.name,{type:e.type}));if(navigator.canShare&&navigator.canShare({files})){try{await navigator.share({files,title:'첨부파일'});return;}catch(e){if(e&&e.name==='AbortError')return;}}const zip=await makeZip(entries),zf=new File([zip],'memo_attachments.zip',{type:'application/zip'});if(navigator.canShare&&navigator.canShare({files:[zf]})){try{await navigator.share({files:[zf],title:'첨부파일'});return;}catch(e){if(e&&e.name==='AbortError')return;}}downloadBlob(zip,'memo_attachments.zip');showToast('ZIP 파일로 저장합니다');return;}const zip=await makeZip(entries);downloadBlob(zip,'memo_attachments.zip');showToast('ZIP 파일로 저장합니다');}catch(e){showToast('내보내기에 실패했습니다');}}
function openBatchExportSheet(targetNotes){const count=targetNotes.reduce((a,n)=>a+(n.media||[]).length,0);if(!count){showToast('내보낼 첨부파일이 없습니다');return;}sheetHost.innerHTML='<div class="sheet"><div class="sh-title">'+count+'개 첨부파일 내보내기</div><div class="sh-item" id="batchShare">↗ 다른 앱으로 공유</div><div class="sh-item" id="batchZip">↓ ZIP으로 저장</div></div><div class="sh-cancel" id="shCancel">취소</div>';sheetBg.classList.add('open');$('batchShare').addEventListener('click',()=>runBatchExport(targetNotes,'share'));$('batchZip').addEventListener('click',()=>runBatchExport(targetNotes,'zip'));$('shCancel').addEventListener('click',closeSheet);}
$('edExport').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(current)openBatchExportSheet([current]);});
$('selectionExport').addEventListener('click',()=>openBatchExportSheet(notes.filter(n=>selectedNoteIds.has(n.id))));
'''
s=s.replace("/* ===== Location alarm (geofence, Haversine like geotask) ===== */",code+"\n/* ===== Location alarm (geofence, Haversine like geotask) ===== */",1)
p.write_text(s,encoding="utf-8")
print("patched export")
