from pathlib import Path
p=Path('silent-camera-safari.html')
s=p.read_text()
old="""// iOS Safari may fail when the same IndexedDB-backed Blob is read more than once.\n// Read each source Blob exactly once, cache an in-memory clone, and create independent\n// object URLs from that clone for list/editor/viewer surfaces.\nconst freshBlobCache=new WeakMap();\nasync function freshBlob(blob){\n  if(!blob || typeof blob.arrayBuffer!=='function') throw new Error('invalid blob');\n  let pending=freshBlobCache.get(blob);\n  if(!pending){\n    pending=(async()=>{\n      const buf=await blob.arrayBuffer();\n      return new Blob([buf],{type:blob.type||'application/octet-stream'});\n    })();\n    freshBlobCache.set(blob,pending);\n  }\n  try{ return await pending; }\n  catch(e){ freshBlobCache.delete(blob); throw e; }\n}\nasync function isolatedBlobURL(blob){\n  const fresh=await freshBlob(blob);\n  return URL.createObjectURL(fresh);\n}\n"""
new="""// iOS Safari may poison a Blob backing store after <video> consumes it.\n// Cache only the source BYTES from IndexedDB once. Every UI surface receives a\n// physically separate Blob built from a copied ArrayBuffer, so thumbnails/editor/viewer\n// never share a Blob backing store with playback.\nconst mediaBytesCache=new WeakMap();\nasync function mediaBytes(blob){\n  if(!blob || typeof blob.arrayBuffer!=='function') throw new Error('invalid blob');\n  let pending=mediaBytesCache.get(blob);\n  if(!pending){\n    pending=(async()=>({buf:await blob.arrayBuffer(),type:blob.type||'application/octet-stream'}))();\n    mediaBytesCache.set(blob,pending);\n  }\n  try{ return await pending; }\n  catch(e){ mediaBytesCache.delete(blob); throw e; }\n}\nasync function isolatedBlobURL(blob){\n  const src=await mediaBytes(blob);\n  const fresh=new Blob([src.buf.slice(0)],{type:src.type});\n  return URL.createObjectURL(fresh);\n}\n"""
if old not in s: raise SystemExit('freshBlob block not found')
s=s.replace(old,new)
old2="""// Do not allow page/editor pinch zoom. Attachment image pinch remains available\n// inside the dedicated viewer because these guards are scoped to #editor only.\neditor.addEventListener('touchmove',e=>{ if(e.touches&&e.touches.length>1)e.preventDefault(); },{passive:false});\neditor.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});\neditor.addEventListener('gesturechange',e=>e.preventDefault(),{passive:false});\n"""
new2="""// Block Safari page pinch globally at capture phase. The dedicated attachment image\n// viewer still implements its own pinch transform on #vwImg; native page zoom is never used.\nfunction blockNativePinch(e){ e.preventDefault(); }\ndocument.addEventListener('gesturestart',blockNativePinch,{passive:false,capture:true});\ndocument.addEventListener('gesturechange',blockNativePinch,{passive:false,capture:true});\ndocument.addEventListener('gestureend',blockNativePinch,{passive:false,capture:true});\ndocument.addEventListener('touchmove',e=>{\n  if(e.touches&&e.touches.length>1){\n    const img=e.target&&e.target.closest?e.target.closest('#vwImg'):null;\n    if(!img) e.preventDefault();\n  }\n},{passive:false,capture:true});\n"""
if old2 not in s: raise SystemExit('editor pinch block not found')
s=s.replace(old2,new2)
p.write_text(s)
